/***
 * DO NOT EDIT THIS FILE IF YOU DON'T KNOW WHAT YOU ARE DOING
 */
 
export default {
	// ================================================================================
	// THEME - Основные настройки темы
	// ================================================================================
	// Главный переключатель для включения/отключения всех плагинов темы
	// Используется в: src/src/services/backupAndRestoreDatastore.ts
	"Elaina-Plugins"				: true,

	// Зарезервировано для принудительного обновления темы
	// В данный момент не используется в коде
	"Force-Update"					: false,

	// Текущая версия CDN сборки
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 79, 84)
	"Cdn-version"					: "",

	// Автоматическое сохранение настроек на сервер при закрытии клиента
	// Используется в: src/src/plugins/settings.ts (строки 36, 71)
	"backup-datastore"				: false,

	// Зарезервировано для отслеживания времени (секунды)
	// В данный момент не используется
	"seconds1"						: 0,

	// Зарезервировано для отслеживания времени (минуты)
	// В данный момент не используется
	"minutes1"						: 0,

	// Зарезервировано для отслеживания времени (часы)
	// В данный момент не используется
	"hours1"						: 0,

	// Состояние паузы аудио (нечетное = на паузе, четное = воспроизводится)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 278, 365, 401, 464, 465, 601)
	'pause-audio'					: 1,

	// Состояние паузы анимации обоев (нечетное = на паузе, четное = воспроизводится)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 187, 193, 623)
  	'pause-wallpaper'				: 1,

	// Глобальное отключение звука (обои + фоновая музыка)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 291, 300, 445, 454, 543, 557, 951, 993)
	'mute-audio'					: false,

	// Счетчик кликов по кнопке "следующие обои" для пасхалки (активируется на 69)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 628, 630, 632)
	"NextBg_Count"					: 0,

	// Громкость звука видео обоев (0.0 - 1.0)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 950)
  	"wallpaper-volume"				: 0.0,

	// Громкость фоновой музыки (0.0 - 1.0)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 450, 538, 567, 992)
  	"audio-volume"					: 0.15,

	// Зацикливание текущего трека (true = повторять, false = следующий в плейлисте)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 306, 317, 615, 1045)
  	"audio-loop"					: false,

	// Зарезервировано для праздничных тем
	// В данный момент не используется в коде
	"Merry-Christmas"				: true,

	// Использовать кастомный UI для поиска очереди
	// Используется в: src/src/theme/loadCustomUi.ts (строка 58)
	"new-gamesearch-queue"			: true,

	// Применять кастомные CSS стили к навигационной панели
	// Используется в: src/src/theme/loadCustomCss.ts (строки 87-90)
	"custom-navbar-css"				: true,

	// Массив отслеживания контента navbar для обнаружения новых вкладок
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 656, 666, 668, 674, 710)
	"navbar-content"				: [],



	// ================================================================================
	// THEME SETTINGS - Кастомизация темы
	// ================================================================================
	// Заглушка для ручного ввода имени файла обоев (плейсхолдер в UI)
	// Не используется в коде (только в интерфейсе настроек)
	"manual-wallpaper-name"			: "Ex: Wallpaper.webm",

	// Заглушка для ручного ввода имени аудиофайла (плейсхолдер в UI)
	// Не используется в коде (только в интерфейсе настроек)
	"manual-audio-name"				: "Ex: Audio.mp3",

	// Заглушка для ручного ввода имени баннера (плейсхолдер в UI)
	// Не используется в коде (только в интерфейсе настроек)
	"manual-banner-name"			: "Ex: Banner.png",

	// Заглушка для ручного ввода имени шрифта (плейсхолдер в UI)
	// Не используется в коде (только в интерфейсе настроек)
	"manual-font-name"				: "Ex: Font.ttf",

	// Режим слайдшоу для автоматической смены обоев
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 264, 267, 966)
	"wallpaper-slideshow"			: false,

	// Интервал времени между сменой обоев в слайдшоу (миллисекунды)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 267)
	"wallpaper-change-slide-time"	: 10000,

	// Автоматически ставить на паузу обои и аудио во время игры
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 1025)
	"turnoff-audio-ingame"			: true,

	// Полностью отключить аудиосистему темы
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 405, 984)
	"Disable-Theme-Audio"			: true,

	// Зарезервировано для предотвращения ручного обновления
	// В данный момент не используется
	"prevent-manual-update"			: false,

	// Зарезервировано для праздничных сообщений
	// В данный момент не используется
	"holiday-message"				: true,

	// Синхронизировать кастомные иконки с сервером (для друзей)
	// Используется в: src/src/plugins/syncUserIcons.ts (строка 79)
	"sync-user-icons"				: true,

	// Скрыть левую боковую панель навигации на главной странице
	// Используется в: src/src/theme/customUI/customHomepage.ts (строки 641, 647, 702, 706, 723, 747)
	"hide-homepage-navbar"			: false,

	// Использовать старые кнопки prev/next вместо выпадающего меню для обоев
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 485)
	"old-prev/next-button"			: false,

	// Показать кнопку для скрытия верхней панели навигации (список друзей)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 1134)
	"enable-hide-top-navbar-friendlist-button": true,

	// Сделать боковую панель прозрачной вместо цветной
	// Используется в: src/src/theme/loadCustomCss.ts (строки 97-99)
  	"sidebar-transparent"			: false,

	// Применить прозрачный фильтр к элементам лобби
	// Используется в: src/src/theme/loadCustomCss.ts (строки 92-94)
	"lobby-transparent-filter"		: true,

	// Сделать диалоговые окна настроек прозрачными
	// Используется в: src/src/theme/loadCustomUi.ts (строка 65)
	"settings-dialogs-transparent"	: true,

	// Скрыть фон страницы профиля
	// Используется в: src/src/theme/loadCustomCss.ts (строки 77-79)
	"hide-profile-background"		: true,

	// Скрыть спларт-арт чемпионов
	// Используется в: src/src/theme/loadCustomCss.ts (строки 72-74)
  	"hide-champions-splash-art"		: true,

	// Скрыть вертикальные разделительные линии в UI
	// Используется в: src/src/theme/loadCustomCss.ts (строки 62-64)
	"hide-vertical-lines"			: true,

	// Показывать кастомное количество RP вместо реального
	// Используется в: src/src/plugins/customBeRp.ts (строка 7)
	"Custom_RP"						: false,

	// Кастомное значение RP для отображения
	// Используется в: src/src/plugins/customBeRp.ts (строки 7, 10)
  	"RP-data"						: "-69",

	// Показывать кастомное количество BE вместо реального
	// Используется в: src/src/plugins/customBeRp.ts (строка 15)
  	"Custom_BE"						: false,

	// Кастомное значение BE для отображения
	// Используется в: src/src/plugins/customBeRp.ts (строка 24)
  	"BE"							: "-69",

	// Показывать кастомное название ранга вместо реального
	// Используется в: src/src/theme/loadCustomUi.ts (строка 47)
	"Custom-Rank-Name"				: true,

	// Первая линия кастомного ранга (основной титул)
	// Используется в: src/src/theme/customUI/customProfile.ts (строка 220)
  	"Rank-line1"					: "Apprentice",

	// Вторая линия кастомного ранга (подзаголовок)
	// Используется в: src/src/theme/customUI/customProfile.ts (строка 223)
  	"Rank-line2"					: "Witch",

	// Использовать кастомный шрифт во всем клиенте
	// Используется в: src/src/theme/loadCustomCss.ts (строка 196)
  	"Custom-Font"					: false,

	// Имя файла текущего выбранного шрифта
	// Используется в: src/src/theme/loadCustomCss.ts (строка 172)
	"CurrentFont"					: "elaina-herculanum_roman.ttf",

	// Список доступных шрифтов для выбора в настройках
	// Используется в UI настроек (выпадающий список)
  	"Font-list"	: [
					"aegirseaborn.ttf",
					"elaina-herculanum_roman.ttf",
					"minecraftregular-bmg3.otf",
					"roboto-medium.ttf"
	],

	// Изменять цвет ника в чате и имен игроков
	// Используется в: src/src/theme/loadCustomCss.ts (строка 198)
	"change-nickname-color"			: true,

	// HEX код цвета ника без прозрачности
	// Используется в: src/src/theme/loadCustomCss.ts (строка 182)
	"nickname-color"				: "#f2c1d0",

	// Значение прозрачности в HEX
	// В данный момент не используется
	"nickname-opacity"				: "ff",

	// Полный HEX код цвета ника с прозрачностью
	// Используется в: src/src/theme/loadCustomCss.ts (строка 182)
	"nickname-color-with-opacity"	: "#f2c1d0ff",

	// Анимированный экран загрузки
	// Используется в: src/src/theme/loadCustomCss.ts (строки 82-84)
  	"animate-loading"				: false,

	// Главный переключатель для всех кастомных иконок
	// Используется в: src/src/theme/loadCustomCss.ts (строка 161)
	"Custom-Icon"					: true,

	// Кастомный значок загрузки (спиннер)
	// Используется в: src/src/theme/loadCustomCss.ts (строки 150-152, 425-427)
	"Custom-Loading-Icon"			: true,

	// Кастомная рамка/бордюр игрока
	// Используется в: src/src/theme/customUI/customIcon.ts (строки 405-407)
	"Custom-Border"					: false,

	// Кастомный баннер регалий на профиле
	// Используется в: src/src/theme/customUI/customIcon.ts (строки 410-412)
	"Custom-Regalia-Banner"			: true,

	// Имя файла текущего баннера
	// Используется в: src/src/theme/customUI/customIcon.ts (строка 209)
	"CurrentBanner"					: "faker_2.png",

	// Список доступных баннеров для выбора в настройках
	// Используется в UI настроек (выпадающий список)
	"Banner-list": [
					"1_winter-noble_2023.png",
					"2_winter-royal_2023.png",
					"3_winter-aurora_2023.png",
					"bee2023.png",
					"challenger.png",
					"lny2023.png",
					"soul-fighters_2023.png",
					"faker_1.png",
					"faker_2.png",
					"arcane_fractured-jinx.png",
					"noxus.png",
	],

	// Кастомный фон для hover-карточек (тултипы информации об игроке)
	// Используется в: src/src/theme/customUI/customIcon.ts (строки 415-417)
	"Custom-Hover-card-backdrop"	: false,

	// Кастомные аватары игроков
	// Используется в: src/src/theme/customUI/customIcon.ts (строки 105-107, 401-403)
  	"Custom-Avatar"					: false,

	// Кастомная иконка RP
	// Используется в: src/src/theme/loadCustomCss.ts (строки 110-112)
	"Custom-RP-Icon"				: false,

	// Кастомная иконка BE
	// Используется в: src/src/theme/loadCustomCss.ts (строки 120-122)
  	"Custom-BE-Icon"				: false,

	// Кастомная иконка ранга
	// Используется в: src/src/theme/loadCustomCss.ts (строки 125-127)
  	"Custom-Rank-Icon"				: false,

	// Кастомная эмблема чести
	// Используется в: src/src/theme/customUI/customIcon.ts (строки 130-132, 429-431)
  	"Custom-Emblem"					: false,

	// Кастомный баннер Clash
	// Используется в: src/src/theme/loadCustomCss.ts (строки 115-117)
  	"Custom-Clash-banner"			: false,

	// Кастомные иконки режимов игры (SR, ARAM, TFT и т.д.)
	// Используется в: src/src/theme/customUI/customIcon.ts (строки 145-147, 420-422)
  	"Custom-Gamemode-Icon"			: true,

	// Кастомная иконка трофея
	// Используется в: src/src/theme/loadCustomCss.ts (строки 140-142)
	"Custom-Trophy"					: false,

	// Кастомные иконки тикера/уведомлений
	// Используется в: src/src/theme/loadCustomCss.ts (строки 135-137)
	"Custom-Ticker"					: false,

	// Кастомный курсор мыши
	// Используется в: src/src/theme/loadCustomCss.ts (строка 197)
  	"Custom-Cursor"					: false,

	// Кастомные фоны для страниц рун
	// Используется в: src/src/theme/loadCustomUi.ts (строка 50)
	"Runes-BG"						: false,

	// Кастомные изображения и имена чемпионов
	// Используется в: src/src/theme/customUI/customChampsBg.ts (строка 20)
	"custom-champs-image"			: false,

	// Скрыть время использования темы
	// В данный момент не используется
	"hide-theme-usage-time"			: false,

	// Скрыть вкладку истории матчей TFT
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 160)
	"hide-tft-match-history"		: false,

	// Скрыть вкладку новостей TFT
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 161)
	"hide-tft-news"					: false,

	// Скрыть вкладку ротационного магазина TFT
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 162)
	"hide-tft-rotational-shop"		: false,

	// Скрыть вкладку сокровищ TFT
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 163)
	"hide-tft-troves"				: false,

	// Скрыть вкладку боевого пропуска TFT
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 164)
	"hide-tft-battle-pass"			: false,

	// Скрыть главную вкладку TFT
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 165)
	"hide-tft-home"					: false,

	// Включить NSFW контент (пасхалки и темы)
	// Используется в: src/src/theme/customUI/customHomepage.ts (строка 630), themeAboutUs.ts
  	"NSFW-Content"					: false,
	
		

	// Plugins settings
	"Old-League-Loader-Settings"	: true,
	"loot-helper"					: true,
  	"auto_accept"					: false,
	"auto_accept_button"			: true,
	"dodge-button"					: true,
	"Enable-Invite-Fr"				: true,
  	"aram-only"						: false,
  	"Auto-Find-Queue"				: false,
	"Gamemode"						: 450,
  	"Create-Delay"					: 15000,
  	"Find-Delay"					: 10000,
	"Custom-profile-hover"			: false,
	"Custom-mastery-score"			: false,
	"Mastery-Score"					: 6969,
	"Custom-rank"					: false,
  	"Ranked Queue ID"				: 2,
  	"Ranked Tier ID"				: 9,
  	"Ranked Division ID"			: 0,
	"Custom-challenge-crystal"		: false,
  	"Challenge-Points"				: 6969,
  	"challengeCrystalLevel"			: 9,
  	"Custom-Status"					: false,
	"Custom-Status-Local"			: false,
  	"status-delay"					: 10000,
	"Name-Spoofer"					: false,
  	"Spoof-name"					: "Elaina Da Catto",
	"Debug-mode"					: false,
  	"Dev-mode"						: false,
	"Active-dev-button"				: 0,
	"Dev-button"					: false,

  	
  	
	// Theme backup
	"System-Info"					: "",
	"last-backup-time"				: "",



	// not use anymore
	"Theme-version"					: "",
	"Elaina-First run"				: false,
  	"buy-all-champs"				: true,
	"ChampsPrice"					: 450,
	"Auto-Honor"					: true,
	"Change-CDN-version"			: false,
	"Hide-linking-settings"			: true,
  	"Hide-verify-acc"				: true,
	"hide-overview"					: true,
  	"hide-merch"					: true,
  	"hide-patch-note"				: true,
  	"hide-esport"					: true,
	"Receive-Update"				: true,
	"April fool` joke"				: false,
}